version: "3"

services:
    app-server-optimists:
        build: .
        ports:
            - "5000:5000"
        environment:
            - PORT=5000
            - MYSQL_DB_NAME=code_samurai_2024
            - MYSQL_USERNAME=root
            - MYSQL_PASSWORD=samurai
            - MYSQL_HOST=database-server-optimists
        depends_on:
            - database-server-optimists

    database-server-optimists:
        image: mysql:latest
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: samurai
            MYSQL_DATABASE: code_samurai_2024
        # volumes:
        #     - database-store:/var/lib/mysql

volumes:
    database-store:
