version: "3"

services:
    app-server:
        build: .
        restart: always
        ports:
            - "8000:8000"
        environment:
            - PORT=8000
            - MYSQL_HOST=database-server
            - MYSQL_PORT=3306
            - MYSQL_USERNAME=root
            - MYSQL_ROOT_PASSWORD=samurai
            - MYSQL_DATABASE=code_samurai_2024
            - REDIS_HOST=redis-server
            - REDIS_PORT=6379
            - JWT_EXPIRY=2629800000
            - JWT_SECRET=f7a30d6b8e03626b78db0e6e958acf57
            - COOKIE_SECRET=9c1a60e5b9fd0b9763c8df7a81e2e32d
            - AUTH_COOKIE_NAME=access_token
        depends_on:
            - database-server
            - redis-server
        volumes:
            - .:/app

    database-server:
        image: mysql:latest
        ports:
            - "3306:3306"
        environment:
            MYSQL_ROOT_PASSWORD: samurai
            MYSQL_DATABASE: code_samurai_2024
        restart: always
        # volumes:
        #     - optimists-db-store:/var/lib/mysql

    redis-server:
        image: redis:latest
        ports:
            - "6380:6379"
        restart: always
        # volumes:
        #     - optimists-redis-store:/data
# volumes:
#     optimists-db-store:
#     optimists-redis-store:
