version: "3"

# use images while deploying

services:
    app-server:
        build: ./api-server
        ports:
            - "8000:8000"
        environment:
            - API_SERVER_PORT
            - MYSQL_HOST
            - MYSQL_PORT
            - MYSQL_USERNAME
            - MYSQL_ROOT_PASSWORD
            - MYSQL_DATABASE
            - REDIS_HOST
            - REDIS_PORT
            - RABBITMQ_HOST
            - JWT_EXPIRY
            - JWT_SECRET
            - COOKIE_SECRET
            - AUTH_COOKIE_NAME
        depends_on:
            - database-server
            - redis-server
        restart: always
        volumes:
            - ./api-server:/app

    email-server:
        build: ./email-server
        ports:
            - "8001:8001"
        environment:
            - EMAIL_SERVER_PORT
        restart: always
        volumes:
            - ./email-server:/app

    database-server:
        image: mysql:latest
        ports:
            - "3306:3306" # Never export port outside in production. Here did for testing purposes.
        environment:
            - MYSQL_ROOT_PASSWORD
            - MYSQL_DATABASE
        restart: always
        # volumes:
        #     - optimists-db-store:/var/lib/mysql

    redis-server:
        image: redis:latest
        ports:
            - "6380:6379" # Never export port outside in production. Here did for testing purposes.
        restart: always
        # volumes:
        #     - optimists-redis-store:/data
# volumes:
#     optimists-db-store:
#     optimists-redis-store:
