version: "3"

services:
    app-server:
        build: .
        ports:
            - "3000:3000"
        environment:
            - PORT=3000
            - MYSQL_DB_NAME=code_samurai_2024
            - MYSQL_USERNAME=root
            - MYSQL_PASSWORD=samurai
            - MYSQL_HOST=database-server
        depends_on:
            - database-server

    database-server:
        image: mysql:latest
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: samurai
            MYSQL_DATABASE: code_samurai_2024
        volumes:
            - database-store:/var/lib/mysql

volumes:
    database-store:
